### PR TITLE
Wellengrafik aktualisieren

### PR DESCRIPTION
**Pull request by Silarn**
From r/place_the_wave - updated graphic with our top banner and additional heart

### CODE REVIEW

**Comment by Silarn** [comment]
We're trying to add a heart with Tunisia to our left

**Review by DRKSLV — APPROVED** [review]

**Comment by Silarn** [comment]
Hold on they moved the heart up now

**Comment by Silarn** [comment]
This should be correct now

**Comment by Silarn** [comment]
Guess it doesn't matter now, have a good night :)

**Pull request closed without merging**
